server:
  port: 8080

logging:
  level:
    root: info

spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  task:
    execution:
      pool:
        core-size: 10
        max-size: 10
      thread-name-prefix: WEATHER-TASK-

    scheduling:
      pool:
        core-size: 10
      thread-name-prefix: WEATHER-SCHEDULER

scheduling:
  living-and-health-idx-scheduler : 0 30 6 * * ?

app-conf:
  api-key: hisooyeon@!
  data-go-kr-key: zhvzvF5vNC7ufu7H%2BQnPJtEQbF2QdNZ0qdvZWLeR%2BnL0UwxwnCgrkmxKB9oqCXVSJp95YTliRHwzxvGdrvjetg%3D%3D